In [ ]:
from google.colab import files

files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"musoye","key":"fc3e44382b0a40e25b48a72123997a63"}'}

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

In [ ]:
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!ls

kaggle.json  sample_data


In [ ]:
!kaggle datasets download -d karakaggle/kaggle-cat-vs-dog-dataset

Dataset URL: https://www.kaggle.com/datasets/karakaggle/kaggle-cat-vs-dog-dataset
License(s): unknown
 99% 783M/787M [00:07<00:00, 144MB/s]
100% 787M/787M [00:07<00:00, 108MB/s]


In [ ]:
!unzip kaggle-cat-vs-dog-dataset.zip -d cats_vs_dogs

Streaming output truncated to the last 5000 lines.
  inflating: cats_vs_dogs/kagglecatsanddogs_3367a/PetImages/Dog/5489.jpg  
  inflating: cats_vs_dogs/kagglecatsanddogs_3367a/PetImages/Dog/549.jpg  
  inflating: cats_vs_dogs/kagglecatsanddogs_3367a/PetImages/Dog/5490.jpg  
  inflating: cats_vs_dogs/kagglecatsanddogs_3367a/PetImages/Dog/5491.jpg  
  inflating: cats_vs_dogs/kagglecatsanddogs_3367a/PetImages/Dog/5492.jpg  
  inflating: cats_vs_dogs/kagglecatsanddogs_3367a/PetImages/Dog/5493.jpg  
  inflating: cats_vs_dogs/kagglecatsanddogs_3367a/PetImages/Dog/5494.jpg  
  inflating: cats_vs_dogs/kagglecatsanddogs_3367a/PetImages/Dog/5495.jpg  
  inflating: cats_vs_dogs/kagglecatsanddogs_3367a/PetImages/Dog/5496.jpg  
  inflating: cats_vs_dogs/kagglecatsanddogs_3367a/PetImages/Dog/5497.jpg  
  inflating: cats_vs_dogs/kagglecatsanddogs_3367a/PetImages/Dog/5498.jpg  
  inflating: cats_vs_dogs/kagglecatsanddogs_3367a/PetImages/Dog/5499.jpg  
  inflating: cats_vs_dogs/kagglecatsanddogs_3367a/

In [ ]:
!ls cats_vs_dogs

kagglecatsanddogs_3367a


In [ ]:
from torchvision.datasets import ImageFolder
from torchvision import transforms
from torch.utils.data import DataLoader


transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize([0.5], [0.5])
])


dataset = ImageFolder(root="cats_vs_dogs", transform=transform)

from torch.utils.data import random_split

train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_dataset, test_dataset = random_split(dataset, [train_size, test_size])

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

print(f"Number of training samples: {len(train_dataset)}")
print(f"Number of testing samples: {len(test_dataset)}")


Number of training samples: 19967
Number of testing samples: 4992


In [ ]:
import torch.nn as nn

model = nn.Sequential(
    nn.Flatten(),
    nn.Linear(3*128*128, 128),
    nn.ReLU(),
    nn.Linear(128, 2)
)
model

Sequential(
  (0): Flatten(start_dim=1, end_dim=-1)
  (1): Linear(in_features=49152, out_features=128, bias=True)
  (2): ReLU()
  (3): Linear(in_features=128, out_features=2, bias=True)
)

In [14]:
import torch

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)
torch.manual_seed(1)
num_epochs = 20

for epoch in range(num_epochs):
  accuracy_hist_train = 0
  for images, labels in train_loader:
    pred = model(images)
    loss = loss_fn(pred, labels)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    is_correct = (
        torch.argmax(pred, dim=1) == labels
        ).float()
    accuracy_hist_train += is_correct.sum()
  accuracy_hist_train /= len(train_loader.dataset)
  print(f'Epoch {epoch + 1} Accuracy '
  f'{accuracy_hist_train:.4f}')

/usr/local/lib/python3.10/dist-packages/PIL/TiffImagePlugin.py:935: UserWarning: Truncated File Read
  warnings.warn(str(msg))


Epoch 1 Accuracy 0.9979
Epoch 2 Accuracy 0.9997
Epoch 3 Accuracy 1.0000
Epoch 4 Accuracy 1.0000
Epoch 5 Accuracy 1.0000
Epoch 6 Accuracy 1.0000
Epoch 7 Accuracy 1.0000
Epoch 8 Accuracy 1.0000
Epoch 9 Accuracy 1.0000
Epoch 10 Accuracy 1.0000
Epoch 11 Accuracy 1.0000
Epoch 12 Accuracy 1.0000
Epoch 13 Accuracy 1.0000
Epoch 14 Accuracy 1.0000
Epoch 15 Accuracy 1.0000
Epoch 16 Accuracy 1.0000
Epoch 17 Accuracy 1.0000
Epoch 18 Accuracy 1.0000
Epoch 19 Accuracy 1.0000
Epoch 20 Accuracy 1.0000


In [25]:
i = 0
for images, labels in test_loader:

  pred = model(images)
  is_correct = (
    torch.argmax(pred, dim=1) ==
    labels
    ).float()
  if i % 50 == 0:
    print(f'Test accuracy: {is_correct.mean():.4f}')
    print(labels)
  i += 1

Test accuracy: 1.0000
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0])
Test accuracy: 1.0000
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0])
Test accuracy: 1.0000
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0])
Test accuracy: 1.0000
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0])


In [19]:
from google.colab import files

files.upload()

Saving dog.jpeg to dog.jpeg


{'dog.jpeg': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x0b\t\t\x07\t\t\x07\t\t\t\t\x0b\t\t\t\t\t\t\x0b\t\x0b\x0b\x0c\x0b\x0b\x0b\x0c\r\x10\x0c\x11\x0e\r\x0e\x0c\x12\x19\x12%\x1a\x1d%\x1d\x19\x1f\x1c))\x16%756\x1a*2>-)0\x19;!\x13\xff\xdb\x00C\x01\x07\x08\x08\x0b\t\x0b\x15\x0b\x0b\x15,\x1d\x19\x1d,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\xff\xc0\x00\x11\x08\x01&\x00\xeb\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1b\x00\x00\x02\x03\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x05\x02\x03\x06\x01\x00\x07\xff\xc4\x00C\x10\x00\x02\x02\x01\x03\x02\x04\x04\x03\x06\x05\x03\x01\x07\x05\x00\x01\x02\x03\x11\x04\x00\x12!\x051\x13"AQ\x14aq\x812\x91\xa1\x06#BR\xb1\xf0\x15b\xc1\xd1\xe1$3\xf1\x82\x07\x16CSr\x92\xa24Ds\xc2\xf2\xff\xc4\x00\x1a\x01\x00\x03\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x03\x04\x01\x05\x00\x06\xff\xc4\x00.\x11\x00\x02\x02\x02\x02\x02\x01\x02\x04\x06\x03\x01\x00\x00\x00\x00\x00\x01\x02\x11

In [20]:
!ls

cats_vs_dogs  dog.jpeg	kaggle-cat-vs-dog-dataset.zip  kaggle.json  sample_data


In [21]:
from PIL import  Image

transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize([0.5], [0.5])
])

image = Image.open('dog.jpeg')
image_tensor = transform(image).unsqueeze(0)  # Add batch dimension

output = model(image_tensor)
output

tensor([[ 8.0681, -8.5951]], grad_fn=<AddmmBackward0>)

In [22]:
files.upload()

Saving cat.jpeg to cat.jpeg


{'cat.jpeg': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x0b\t\t\x07\t\t\x07\t\t\t\t\x0b\t\t\t\t\t\t\x0b\t\x0b\x0b\x0c\x0b\x0b\x0b\x0c\r\x10\x0c\x11\x0e\r\x0e\x0c\x12\x19\x12%\x1a\x1d%\x1d\x19\x1f\x1c))\x16%756\x1a*2>-)0\x19;!\x13\xff\xdb\x00C\x01\x07\x08\x08\x0b\t\x0b\x15\x0b\x0b\x15,\x1d\x19\x1d,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\xff\xc0\x00\x11\x08\x01\x0e\x01\x00\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1c\x00\x00\x01\x05\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\xff\xc4\x00=\x10\x00\x02\x01\x03\x02\x04\x04\x04\x04\x05\x02\x06\x02\x03\x00\x00\x01\x02\x11\x00\x03!\x04\x12\x051AQ\x13"aq\x062\x81\x91\x14\xa1\xb1\xf0#BR\xc1\xd1\x15\xf1\x073br\x82\xe1C\x92\x16\xa2\xc2\xff\xc4\x00\x18\x01\x00\x03\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\xff\xc4\x00!\x11\x00\x03\x01\x00\x02\x02\x03\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x01\x11\x02!1\x03\x12

In [23]:
!ls

cat.jpeg  cats_vs_dogs	dog.jpeg  kaggle-cat-vs-dog-dataset.zip  kaggle.json  sample_data


In [24]:
from PIL import  Image

transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize([0.5], [0.5])
])

image = Image.open('cat.jpeg')
image_tensor = transform(image).unsqueeze(0)  # Add batch dimension

output = model(image_tensor)
output

tensor([[ 12.9250, -12.9952]], grad_fn=<AddmmBackward0>)

In [26]:
torch.save(model.state_dict(), 'cat_dog.ph')

In [27]:
!ls

cat_dog.ph  cats_vs_dogs  kaggle-cat-vs-dog-dataset.zip  sample_data
cat.jpeg    dog.jpeg	  kaggle.json


In [28]:
files.download('cat_dog.ph')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>